=== islandskan/islandskan-workbench/src/_data/bookshelf.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "itemId": {
                "type": "integer",
                "minimum": 1,
                "description": "Unique, auto increment identifier for the item"
            },
            "type": {
                "type": "string",
                "description": "The type of bookshelf item; book, article, video, movie, series, game, music, podcast, learning resource, audiobook, other people's projects"
            },
            "title": {
                "type": "string",
                "description": "The title/name of the item"
            },
            "dateAdded": {
                "type": "string",
                "description": "Dat the item was added to the Bookshelf (YYYY-MM-DD)",
                "format": "date"
            },
            "creator": {
                "type": ["string", "null"],
                "description": "Name of author, writer, artist, director, or other creator of the listed item"
            },
            "year": {
                "type": ["integer", "null"],
                "minimum": 1000,
                "maximum": 9999,
                "description": "The year the item was released/published"
            },
            "description": {
                "type": ["string", "null"],
                "description": "A short description about the item"
            },
            "externalURI": {
                "type": ["string", "null"],
                "format": "uri",
                "description": "Optional, external link. Absolute URI allowed(protocol+host+path)"
            },
            "relatedThoughtURI": {
                "type": ["string", "null"],
                "format": "uri-reference",
                "description": "Optional link to related Thought post. Absolute(protocol+host+path) and relative URI(relative to root or to file location) allowed"
            }
        },
        "required": ["itemId", "type", "title", "dateAdded"],
        "additionalProperties": false
    }
}

=== islandskan/islandskan-workbench/src/_data/bookshelf.json
[
    {
        "itemId": 1,
        "type": "book",
        "title": "Data and Communications signal",
        "dateAdded": "2025-08-15",
        "creator": null,
        "year": null,
        "description": null,
        "externalURI": null,
        "relatedThoughtURI": null
    },
    {
        "itemId": 2,
        "type": "book",
        "title": "Technofeminism",
        "dateAdded": "2025-08-17",
        "creator": null,
        "year": null,
        "description": null,
        "externalURI": null,
        "relatedThoughtURI": null
    },
    {
        "itemId": 3,
        "type": "game",
        "title": "Clair Obscur Expedition 33",
        "dateAdded": "2025-10-05",
        "creator": "Sandfall",
        "year": 2025,
        "description": null,
        "externalURI": "https://www.expedition33.com/",
        "relatedThoughtURI": null
    },
    {
        "itemId": 4,
        "type": "video",
        "title": "Nintendo 64 Jungle mix",
        "dateAdded": "2025-10-05",
        "creator": "",
        "year": 2021,
        "description": null,
        "externalURI": "https://www.youtube.com/watch?v=uLxD4ozDPZA&t=3s",
        "relatedThoughtURI": null
    }
]
